#!/usr/bin/env node

var builder = require('buildify'),
    path = require('path');

var baseDir = __dirname + '/..',
    sourceDir = baseDir + '/src',
    outputDir = baseDir + '/distribution';

//Files to concatenate into main file
var fileList = [
  'lib/underscore.mixin.deepExtend.js',
  'src/deep-model.js'
];

//Concatenate the main files
builder(baseDir)
  .concat(fileList)
  .save('distribution/deep-model.js')
  .uglify()
  .save('distribution/deep-model.min.js');
